### ISSUE TITLE
Weitere Zeichen in Transkription erlauben

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/bts#150]
Transkriptions-Blockwart, erlauben:
- Koptisch: zusätzlich: **U+03E2-U+03EF** <= https://redmine.bbaw.de/issues/16460
- Griechisch:   <= https://redmine.bbaw.de/issues/16460 
  - **U+0384- U+03E1 ; U+03F0-U+03FF ; U+1F00-U+1FFE** (zu überprüfen, ob alles erwischt) 
  - Unterpunkt (griechische Philologie): **U+0323**
- Arabisch: 
  - |'\u0600'..'\u06FF'|'\u0750'..'\u077F'|'\u0870'..'\u08FF'|'\uFB50'..'\uFBC2'|'\uFBD3..\uFDFF'
  - Richtungssteuerzeichen (rtl/ltr): U+2066-U+2069
- Hieroglyphisch: U+13000 - U+13455
- Bullet: U+2022 (auch/oder U+00B0?), 
- Middle dot: **U+00B7**
- Backslash: U+005C <= https://redmine.bbaw.de/issues/16462
- Egyptological Yod: U+A7BC/U+A7BD <= Leiden Unified Transliteration; https://redmine.bbaw.de/issues/16460
- Nullmorphem: **U+00F8**
- Mathematical brackets: U+27E6-U+27EB <= https://redmine.bbaw.de/issues/16462
- Doppelte runde: U+2E28, U+2E29
- Elipsis: U+2026
- Doppelter schräggestellter Bindestrich: U+2E17  <= https://redmine.bbaw.de/issues/16460
- Pfeile: U+2190-U+2193
- Combining Overlines (Math): U+0305, U+033F 
- Akzente (standalone) für Einfügung über/unter Zeile: U+0060, U+00B4

Auch Sortierreichenfolge bzgl. dieser Zeichen erweitern

**Comment by S0bi** [comment]
`RULE_EGYSTRING : ('\uA722'|'\uA723'|'\u02BE'|'\uA725'|'\uA724'|'j'|'y'|'w'|'b'|'f'|'m'|'n'|'r'|'h'|'\u1E25'|'\u1E2B'|'\u1E96'|'H'|'\u1E24'|'\u1E2A'|'H\u0331'|'H\u032D'|'z'|'s'|'\u0161'|'S'|'\u0160'|'q'|'k'|'g'|'t'|'\u1E6F'|'\u1E71'|'T'|'\u1E6E'|'\u1E70'|'d'|'\u1E0F'|'\u1E0E'|'h\u032D'|'i'|'i\u032F'|'\u0131\u0357'|'\u0131\u0357\u032F'|'\u00EF'|'i\u032D'|'I\u0357'|'I'|'I\u032F'|'i\u032F\u032F'|'\u00CF'|'u'|'u\u032F'|'U'|'U\u032F'|'e'|'/'|'+'|'a'|'J'|'Y'|'W'|'B'|'P'|'F'|'M'|'N'|'R'|'L'|'Z'|'Q'|'K'|'G'|'D'|'A'|'\u2C80'..'\u2CFF'|'p'|'l'|'='|'_'|'\u205D'|'0'..'9'|'\u00D5'|'\u00E3'|'\u00DE'|'!'|'\u0152'|'\u0153'|'\u0178'|'\u00C6'|'*'|'\u00EA'|'\u03E2'...'\u03EF'|'\u0384'...'\u03E1'|'\u03F0'...'\u03FF'|'\u1F00'...'\u1FFE'|'\u0323'|'\u00F8'|'\u00B7')+;`

 angepasst in InternatEgyDsl.g im Paket bts.corpus.text.egy.egydsl.ui

**Comment by S0bi** [comment]
Erlaubte Zeichen:
```
'\uA723'|'\uA722' // Aleph
 |'\u02BE'   // spiLen
 |'\uA725'|'\uA724' // Ajin
 |'j'|'y'|'w'|'b'|'f'|'m'|'n'|'r'
 |'h'|'ḥ'|'ḫ'|'ẖ'|'H'|'Ḥ'|'Ḫ'|'H̱'|'H̭'
 |'z'
 |'s'|'š'|'S'|'Š'
 |'Ś'|'ś' // Schenkelsche Zeichen
 |'q'|'k'|'g'
 |'t'|'ṯ'|'ṱ'|'T'|'Ṯ'|'Ṱ'
 |'ṭ' |'Ṭ' // Schenkelsche Zeichen 
 |'d'|'ḏ'|'Ḏ'
 |'h̭'
 |'i'|'i̯' |'i̯̯'|'ı͗'|'ı̯͗'|'i̭'|'I͗'|'I'|'I̯'
 |'\uA7BC'|'\uA7BD' // Egyptological Yod
 |'ï'|'Ï'   // ITrema
 |'ḳ'|'Ḳ' // Schenkelsche Zeichen 
 |'u'|'u̯'|'U'|'\u0055\u032F'
 |'e'|'+'
 |'č'|'Č'//funst |'č̣'|'Č̣' // Schenkelsche Zeichen
 |'a'|'J'|'Y'|'W'|'B'|'P'|'F'|'M'
 |'N'|'R'|'L'
 |'Z'|'Q'|'K'|'G'|'D'
 |'A'
 |'p'|'l' 
//interfix :
|'='
|'\u2E17' // Oblique equal
|'_'
|'\u205D'   // trplColon	
//num
|'0'..'9'	
// special
|'Õ'|'ã'|'Þ'|'!'
|'\u0152'   // OElig
|'\u0153'   // oelig
|'\u0178'   // Yuml
|'\u00C6'
|'*'|'ê'
// Coptic
|'\u2C80'..'\u2CFF'
|'\u03E2'..'\u03EF' 
// Greek
|'\u0384'..'\u03E1'
|'\u03F0'..'\u03FF' 
|'\u1F00'..'\u1FFE' 
|'\u0323' // Dot below
// Arabic
|'\u0600'..'\u06FF'|'\u0750'..'\u077F'|'\u0870'..'\u08FF'|'\uFB50'..'\uFBC2'|'\uFBD3'..'\uFDFF'
|'\u2066'..'\u2069' // RTL, LTR 
// variae
|'\u2022'|'\u00B0' // Bullet
|'\u00B7' // Middle Dot 
|'/'|'\\' // Slash, Backslash
|'\u0060'|'\u00B4' // Standalone accents 
|'\u00F8' // Zero morpheme
|'\u2026' // Ellipsis 
|'\u2190'..'\u2193' // Arrows
|'\u0305'|'\u033F' // Combining overlines 
```

Optisch
'ꜣ'|'Ꜣ' // Aleph
|'ʾ' // spiLen
|'ꜥ'|'Ꜥ' // Ajin
|'j'|'y'|'w'|'b'|'f'|'m'|'n'|'r'
|'h'|'ḥ'|'ḫ'|'ẖ'|'H'|'Ḥ'|'Ḫ'|'H̱'|'H̭'
|'z'
|'s'|'š'|'S'|'Š'
|'Ś'|'ś' // Schenkelsche Zeichen
|'q'|'k'|'g'
|'t'|'ṯ'|'ṱ'|'T'|'Ṯ'|'Ṱ'
|'ṭ' |'Ṭ' // Schenkelsche Zeichen
|'d'|'ḏ'|'Ḏ'
|'h̭'
|'i'|'i̯' |'i̯̯'|'ı͗'|'ı̯͗'|'i̭'|'I͗'|'I'|'I̯'
|'Ꞽ'|'ꞽ' // Egyptological Yod keine Darstellung aber funst
|'ï'|'Ï' // ITrema
|'ḳ'|'Ḳ' // Schenkelsche Zeichen
|'u'|'u̯'|'U'|'U̯'
|'e'|'+'
|'č'|'Č' |'č̣'|'Č̣' // Schenkelsche Zeichen
|'a'|'J'|'Y'|'W'|'B'|'P'|'F'|'M'
|'N'|'R'|'L'
|'Z'|'Q'|'K'|'G'|'D'
|'A'
|'p'|'l'
//interfix :
|'='
|'⸗' // Oblique equal
// |':'|'='|'≡'|','|'.'|'~'|'⋮' // these interfixes below
|'_'
|'⁝' // trplColon
//num
|'0'..'9'
// special
|'Õ'|'ã'|'Þ'|'!'
|'Œ' // OElig
|'œ' // oelig
|'Ÿ' // Yuml
|'Æ'
|'*'|'ê'
// Coptic
|'Ⲁ'..'⳿'
|'Ϣ'..'ϯ'
// Greek
|'΄'..'ϡ'
|'ϰ'..'Ͽ'
|'ἀ'..'῾'
|'̣' // Dot below
// Arabic
|'؀'..'ۿ'|'ݐ'..'ݿ'|'ࡰ'..'ࣿ'|'ﭐ'..'﯂'|'ﯓ'..'﷿'
|'⁦'..'⁩' // RTL, LTR
// variae
|'•'|'°' // Bullet
|'·' // Middle Dot
|'/'|'\\' // Slash, Backslash
|'`'|'´' // Standalone accents
|'ø' // Zero morpheme
|'…' // Ellipsis
|'←'..'↓' // Arrows
|'̅'|'̿' // Combining overlines
